/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/3SMTnRSx9UP
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button";
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

export default function Starfinder() {
  return (
    <div className="flex flex-col h-screen bg-[#0F1218] text-white">
      <header className="bg-[#1C2026] px-6 py-4 flex items-center justify-between">
        <div className="flex items-center gap-4">
          <SpaceIcon className="w-8 h-8" />
          <h1 className="text-2xl font-bold">Starfinder Society</h1>
        </div>
        <div className="flex items-center gap-4">
          <Button variant="ghost" size="icon">
            <FilterIcon className="w-6 h-6" />
          </Button>
          <Button variant="ghost" size="icon">
            <SearchIcon className="w-6 h-6" />
          </Button>
          <Avatar>
            <AvatarImage src="/placeholder-user.jpg" />
            <AvatarFallback>CS</AvatarFallback>
          </Avatar>
        </div>
      </header>
      <main className="flex-1 p-6 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 overflow-y-auto">
        <Card className="bg-[#1C2026] rounded-2xl p-6 flex flex-col gap-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <div className="bg-[#2E3440] rounded-full p-2 flex items-center justify-center">
                <ContainerIcon className="w-6 h-6 text-[#81A1C1]" />
              </div>
              <h3 className="text-xl font-bold">Cargo Retrieval</h3>
            </div>
            <Badge
              variant="outline"
              className="bg-[#2E3440] border-[#81A1C1] text-[#81A1C1]"
            >
              Easy
            </Badge>
          </div>
          <p className="text-[#D8DEE9]">
            Retrieve a valuable cargo shipment from a remote asteroid field and
            deliver it to the Starfinder Society headquarters.
          </p>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <UsersIcon className="w-4 h-4 text-[#81A1C1]" />
              <span className="text-[#D8DEE9]">Starfinder Society</span>
            </div>
            <div className="flex items-center gap-2">
              <CoinsIcon className="w-4 h-4 text-[#81A1C1]" />
              <span className="text-[#D8DEE9]">5,000 Credits</span>
            </div>
          </div>
        </Card>
        <Card className="bg-[#1C2026] rounded-2xl p-6 flex flex-col gap-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <div className="bg-[#2E3440] rounded-full p-2 flex items-center justify-center">
                <SpaceIcon className="w-6 h-6 text-[#81A1C1]" />
              </div>
              <h3 className="text-xl font-bold">Alien Diplomacy</h3>
            </div>
            <Badge
              variant="outline"
              className="bg-[#2E3440] border-[#81A1C1] text-[#81A1C1]"
            >
              Moderate
            </Badge>
          </div>
          <p className="text-[#D8DEE9]">
            Negotiate a trade agreement with a reclusive alien civilization and
            secure valuable resources for the Starfinder Society.
          </p>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <UsersIcon className="w-4 h-4 text-[#81A1C1]" />
              <span className="text-[#D8DEE9]">Alien Consortium</span>
            </div>
            <div className="flex items-center gap-2">
              <CoinsIcon className="w-4 h-4 text-[#81A1C1]" />
              <span className="text-[#D8DEE9]">10,000 Credits</span>
            </div>
          </div>
        </Card>
        <Card className="bg-[#1C2026] rounded-2xl p-6 flex flex-col gap-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <div className="bg-[#2E3440] rounded-full p-2 flex items-center justify-center">
                <BombIcon className="w-6 h-6 text-[#81A1C1]" />
              </div>
              <h3 className="text-xl font-bold">Pirate Raid</h3>
            </div>
            <Badge
              variant="outline"
              className="bg-[#2E3440] border-[#81A1C1] text-[#81A1C1]"
            >
              Hard
            </Badge>
          </div>
          <p className="text-[#D8DEE9]">
            Intercept and neutralize a pirate fleet that has been raiding
            Starfinder Society supply lines, recovering any stolen cargo.
          </p>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <UsersIcon className="w-4 h-4 text-[#81A1C1]" />
              <span className="text-[#D8DEE9]">Starfinder Society</span>
            </div>
            <div className="flex items-center gap-2">
              <CoinsIcon className="w-4 h-4 text-[#81A1C1]" />
              <span className="text-[#D8DEE9]">20,000 Credits</span>
            </div>
          </div>
        </Card>
        <Card className="bg-[#1C2026] rounded-2xl p-6 flex flex-col gap-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <div className="bg-[#2E3440] rounded-full p-2 flex items-center justify-center">
                <TelescopeIcon className="w-6 h-6 text-[#81A1C1]" />
              </div>
              <h3 className="text-xl font-bold">Stellar Mapping</h3>
            </div>
            <Badge
              variant="outline"
              className="bg-[#2E3440] border-[#81A1C1] text-[#81A1C1]"
            >
              Moderate
            </Badge>
          </div>
          <p className="text-[#D8DEE9]">
            Chart a previously unexplored region of space, mapping stellar
            phenomena and potential hazards for the Starfinder Society&apos;s
            navigational databases.
          </p>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <UsersIcon className="w-4 h-4 text-[#81A1C1]" />
              <span className="text-[#D8DEE9]">Starfinder Society</span>
            </div>
            <div className="flex items-center gap-2">
              <CoinsIcon className="w-4 h-4 text-[#81A1C1]" />
              <span className="text-[#D8DEE9]">15,000 Credits</span>
            </div>
          </div>
        </Card>
        <Card className="bg-[#1C2026] rounded-2xl p-6 flex flex-col gap-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <div className="bg-[#2E3440] rounded-full p-2 flex items-center justify-center">
                <SpaceIcon className="w-6 h-6 text-[#81A1C1]" />
              </div>
              <h3 className="text-xl font-bold">Alien Artifact Retrieval</h3>
            </div>
            <Badge
              variant="outline"
              className="bg-[#2E3440] border-[#81A1C1] text-[#81A1C1]"
            >
              Hard
            </Badge>
          </div>
          <p className="text-[#D8DEE9]">
            Recover a valuable alien artifact from a dangerous and unexplored
            world, and deliver it safely to the Starfinder Society&apos;s
            research labs.
          </p>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <UsersIcon className="w-4 h-4 text-[#81A1C1]" />
              <span className="text-[#D8DEE9]">Alien Consortium</span>
            </div>
            <div className="flex items-center gap-2">
              <CoinsIcon className="w-4 h-4 text-[#81A1C1]" />
              <span className="text-[#D8DEE9]">25,000 Credits</span>
            </div>
          </div>
        </Card>
        <Card className="bg-[#1C2026] rounded-2xl p-6 flex flex-col gap-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <div className="bg-[#2E3440] rounded-full p-2 flex items-center justify-center">
                <SpaceIcon className="w-6 h-6 text-[#81A1C1]" />
              </div>
              <h3 className="text-xl font-bold">Escort Mission</h3>
            </div>
            <Badge
              variant="outline"
              className="bg-[#2E3440] border-[#81A1C1] text-[#81A1C1]"
            >
              Easy
            </Badge>
          </div>
          <p className="text-[#D8DEE9]">
            Provide safe passage and escort for a high-profile Starfinder
            Society diplomat through a dangerous sector of space.
          </p>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <UsersIcon className="w-4 h-4 text-[#81A1C1]" />
              <span className="text-[#D8DEE9]">Starfinder Society</span>
            </div>
            <div className="flex items-center gap-2">
              <CoinsIcon className="w-4 h-4 text-[#81A1C1]" />
              <span className="text-[#D8DEE9]">8,000 Credits</span>
            </div>
          </div>
        </Card>
      </main>
    </div>
  );
}

function BombIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="13" r="9" />
      <path d="M14.35 4.65 16.3 2.7a2.41 2.41 0 0 1 3.4 0l1.6 1.6a2.4 2.4 0 0 1 0 3.4l-1.95 1.95" />
      <path d="m22 2-1.5 1.5" />
    </svg>
  );
}

function CoinsIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="8" cy="8" r="6" />
      <path d="M18.09 10.37A6 6 0 1 1 10.34 18" />
      <path d="M7 6h1v4" />
      <path d="m16.71 13.88.7.71-2.82 2.82" />
    </svg>
  );
}

function ContainerIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 7.7c0-.6-.4-1.2-.8-1.5l-6.3-3.9a1.72 1.72 0 0 0-1.7 0l-10.3 6c-.5.2-.9.8-.9 1.4v6.6c0 .5.4 1.2.8 1.5l6.3 3.9a1.72 1.72 0 0 0 1.7 0l10.3-6c.5-.3.9-1 .9-1.5Z" />
      <path d="M10 21.9V14L2.1 9.1" />
      <path d="m10 14 11.9-6.9" />
      <path d="M14 19.8v-8.1" />
      <path d="M18 17.5V9.4" />
    </svg>
  );
}

function FilterIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3" />
    </svg>
  );
}

function SearchIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  );
}

function SpaceIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 17v1c0 .5-.5 1-1 1H3c-.5 0-1-.5-1-1v-1" />
    </svg>
  );
}

function TelescopeIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m10.065 12.493-6.18 1.318a.934.934 0 0 1-1.108-.702l-.537-2.15a1.07 1.07 0 0 1 .691-1.265l13.504-4.44" />
      <path d="m13.56 11.747 4.332-.924" />
      <path d="m16 21-3.105-6.21" />
      <path d="M16.485 5.94a2 2 0 0 1 1.455-2.425l1.09-.272a1 1 0 0 1 1.212.727l1.515 6.06a1 1 0 0 1-.727 1.213l-1.09.272a2 2 0 0 1-2.425-1.455z" />
      <path d="m6.158 8.633 1.114 4.456" />
      <path d="m8 21 3.105-6.21" />
      <circle cx="12" cy="13" r="2" />
    </svg>
  );
}

function UsersIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>
  );
}
